<?php
$z[0]=Array("field","",319,338);
$z[0][4]['name']="title";
$z[1]=Array("global","",339,365);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",406,428);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",468,519);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1160,1195);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1680,1699);
$z[5][4]['name']="title";
$z[6]=Array("field","",1756,1776);
$z[6][4]['name']="writer";
$z[7]=Array("field","",1818,1874);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[8]=Array("field","",1910,1930);
$z[8][4]['name']="source";
$z[9]=Array("field","",2115,2133);
$z[9][4]['name']="body";
$z[10]=Array("include","",2259,2296);
$z[10][4]['filename']="footer.htm";

?>