<?php
$z[0]=Array("field","",319,338);
$z[0][4]['name']="title";
$z[1]=Array("global","",339,365);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",406,428);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",468,519);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1160,1195);
$z[4][4]['filename']="head.htm";
$z[5]=Array("global","",1542,1567);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("channel","\r\n          <div class=\"span2 col-xs-4\"> <a href=\"[field:typelink/]\" class=\"support_type_list normal\" title=\"[field:typename/]\">[field:typename/]</a> </div>\r\n          ",2354,2704);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<div class='span2 col-xs-4'><a href='~typelink~' class='support_type_list active'>~typename~</a></div>";
$z[7]=Array("channel","\r\n                  <li> <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n                  ",3243,3408);
$z[7][4]['type']="son";
$z[8]=Array("field","",3752,3771);
$z[8][4]['name']="title";
$z[9]=Array("field","",3836,3856);
$z[9][4]['name']="writer";
$z[10]=Array("field","",3903,3959);
$z[10][4]['name']="pubdate";
$z[10][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[11]=Array("field","",3999,4019);
$z[11][4]['name']="source";
$z[12]=Array("field","",4138,4156);
$z[12][4]['name']="body";
$z[13]=Array("include","",4285,4322);
$z[13][4]['filename']="footer.htm";

?>