<div class="case_show_list wow fadeInUp">
            <div class="span7 col-xm-6 col-sm-12">
              <div class="case_show_pic"><img src="[field:picname/]" alt="[field:title/]" /></div>
            </div>
            <div class="span5 col-xm-6 col-sm-12">
              <div class="case_show_brief">
                <h3 class="case_show_brief_title"><span></span>[field:title/]</h3>
                <div class="case_show_brief_text">
                  <p>[field:description function="cn_substr(@me,400)"/]...</p>
                </div>
                <div class="case_show_brief_button"> <a href="[field:wz/]" title="[field:title/]" class=" all_button" target="_blank">查看站点</a> </div>
              </div>
            </div>
          </div>