<div class="span6 col-sm-12"> <a  href="[field:arcurl/]">
                      <div class="kzf-mod-wrap wow fadeInUp">
                        <div class="kzf-mod-pic"> <img src="[field:litpic/]" alt="[field:title/]" /> </div>
                        <div class="kzf-mod-title">
                          <p>[field:title/]</p>
                        </div>
                      </div>
                      </a> </div>