<?php
$z[0]=Array("channelartlist","\r\n                    <li> <a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a> </li>\r\n                    ",689,910);
$z[0][4]['typeid']="top";
$z[1]=Array("flink","\r\n                  <li>[field:link /]</li>\r\n                  ",1275,1410);
$z[1][4]['row']="24";
$z[1][4]['type']="text";
$z[1][4]['titlelen']="24";
$z[1][4]['typeid']="0";
$z[2]=Array("global","",1825,1846);
$z[2][4]['name']="cfg_dz";
$z[3]=Array("global","",1980,2001);
$z[3][4]['name']="cfg_dh";
$z[4]=Array("global","",2016,2037);
$z[4][4]['name']="cfg_dh";
$z[5]=Array("global","",2171,2198);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",2215,2242);
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("global","",2367,2388);
$z[7][4]['name']="cfg_yx";
$z[8]=Array("global","",2544,2570);
$z[8][4]['name']="cfg_powerby";
$z[9]=Array("global","",2571,2595);
$z[9][4]['name']="cfg_beian";

?>