<?php
$z[0]=Array("global","",180,206);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","(@me==\"\")? @me=\" class='active' \":@me=\"\";",512,603);
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("channel","\r\n          <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n          ",646,892);
$z[2][4]['type']="top";
$z[2][4]['currentstyle']="<li><a href='~typelink~' class='active'>~typename~</a></li>";
$z[3]=Array("type"," <a href=\"[field:typelink/]\" target=\"_blank\" title=\"合作\"><img src=\"/skin/images/057.png\" alt=\"合作\" />合作</a>",1023,1174);
$z[3][4]['typeid']="9";
$z[4]=Array("type"," <a href=\"[field:typelink/]\"><img src=\"/skin/images/060.png\" alt=\"建站帮助中心\" />帮助</a>",1461,1594);
$z[4][4]['typeid']="14";
$z[5]=Array("global","",1976,1997);
$z[5][4]['name']="cfg_qq";
$z[6]=Array("global","",2281,2302);
$z[6][4]['name']="cfg_qq";
$z[7]=Array("global","",2592,2613);
$z[7][4]['name']="cfg_qq";
$z[8]=Array("arclist","\r\n      <li><span></span><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></li>\r\n      ",3027,3197);
$z[8][4]['row']="5";
$z[8][4]['typeid']="14";
$z[8][4]['titlelen']="58";

?>