<?php
$z[0]=Array("global","",319,345);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",389,419);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",456,483);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1181,1216);
$z[3][4]['filename']="head.htm";
$z[4]=Array("global","",1775,1796);
$z[4][4]['name']="cfg_qq";
$z[5]=Array("global","",2517,2538);
$z[5][4]['name']="cfg_qq";
$z[6]=Array("global","",18393,18414);
$z[6][4]['name']="cfg_qq";
$z[7]=Array("arclist","\r\n                  <li class=\"span12\"> <a href=\"[field:arcurl/]\" class=\"span8\" title=\"[field:title/]\"><i class=\"fa fa-angle-right\"></i>[field:title/] </a>\r\n                    <div style=\"font-size: 12px; color: #ccc; float: right; margin-top: 3px;\">[field:pubdate function=\"MyDate('m-d',@me)\"/]</div>\r\n                  </li>\r\n                  ",19250,19662);
$z[7][4]['row']="5";
$z[7][4]['typeid']="11";
$z[7][4]['titlelen']="58";
$z[8]=Array("arclist","\r\n                  <li class=\"span12\"> <a href=\"[field:arcurl/]\" class=\"span8\" title=\"[field:title/]\"><i class=\"fa fa-angle-right\"></i>[field:title/] </a>\r\n                    <div style=\"font-size: 12px; color: #ccc; float: right; margin-top: 3px;\">[field:pubdate function=\"MyDate('m-d',@me)\"/]</div>\r\n                  </li>\r\n                  ",20059,20471);
$z[8][4]['row']="5";
$z[8][4]['typeid']="13";
$z[8][4]['titlelen']="58";
$z[9]=Array("arclist","\r\n                  <li class=\"span12\"> <a href=\"[field:arcurl/]\" class=\"span8\" title=\"[field:title/]\"><i class=\"fa fa-angle-right\"></i>[field:title/] </a>\r\n                    <div style=\"font-size: 12px; color: #ccc; float: right; margin-top: 3px;\">[field:pubdate function=\"MyDate('m-d',@me)\"/]</div>\r\n                  </li>\r\n                  ",20870,21282);
$z[9][4]['row']="5";
$z[9][4]['typeid']="12";
$z[9][4]['titlelen']="58";
$z[10]=Array("include","",21473,21510);
$z[10][4]['filename']="footer.htm";

?>