<?php
$z[0]=Array("field","",319,338);
$z[0][4]['name']="title";
$z[1]=Array("global","",339,365);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",406,435);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",475,533);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1237,1272);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n      <div class=\"span2 col-xs-4\"> <a href=\"[field:typelink/]\" class=\"support_type_list normal\" title=\"[field:typename/]\">[field:typename/]</a> </div>\r\n      ",2070,2404);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<div class='span2 col-xs-4'><a href='~typelink~' class='support_type_list active'>~typename~</a></div>";
$z[6]=Array("list","\r\n          <div class=\"case_show_list wow fadeInUp\">\r\n            <div class=\"span7 col-xm-6 col-sm-12\">\r\n              <div class=\"case_show_pic\"><img src=\"[field:picname/]\" alt=\"[field:title/]\" /></div>\r\n            </div>\r\n            <div class=\"span5 col-xm-6 col-sm-12\">\r\n              <div class=\"case_show_brief\">\r\n                <h3 class=\"case_show_brief_title\"><span></span>[field:title/]</h3>\r\n                <div class=\"case_show_brief_text\">\r\n                  <p>[field:description function=\"cn_substr(@me,400)\"/]...</p>\r\n                </div>\r\n                <div class=\"case_show_brief_button\"> <a href=\"[field:wz/]\" title=\"[field:title/]\" class=\" all_button\" target=\"_blank\">查看站点</a> </div>\r\n              </div>\r\n            </div>\r\n          </div>\r\n          ",2579,3425);
$z[6][4]['pagesize']="10";
$z[6][4]['channelid']="17";
$z[7]=Array("global","",3666,3687);
$z[7][4]['name']="cfg_qq";
$z[8]=Array("global","",3829,3850);
$z[8][4]['name']="cfg_qq";
$z[9]=Array("include","",3971,4008);
$z[9][4]['filename']="footer.htm";

?>