<?php
$z[0]=Array("field","",319,338);
$z[0][4]['name']="title";
$z[1]=Array("global","",339,365);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",406,435);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",475,533);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1174,1209);
$z[4][4]['filename']="head.htm";
$z[5]=Array("global","",1556,1581);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("channel","\r\n          <div class=\"span2 col-xs-4\"> <a href=\"[field:typelink/]\" class=\"support_type_list normal\" title=\"[field:typename/]\">[field:typename/]</a> </div>\r\n          ",2368,2718);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<div class='span2 col-xs-4'><a href='~typelink~' class='support_type_list active'>~typename~</a></div>";
$z[7]=Array("channel","\r\n                <li class=\"\"> <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n                ",3252,3422);
$z[7][4]['type']="son";
$z[8]=Array("field","",3684,3713);
$z[8][4]['name']="typename";
$z[9]=Array("list","\r\n                <li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n                  <div class=\"text\">[field:title/]\r\n                    <div style=\"float:right\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</div>\r\n                  </div>\r\n                  </a> </li>\r\n                ",3757,4093);
$z[9][4]['pagesize']="10";
$z[10]=Array("pagelist","",4274,4340);
$z[10][4]['listitem']="index,end,pre,next,pageno";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",4619,4656);
$z[11][4]['filename']="footer.htm";

?>